### ISSUE TITLE
Komp Baniaka do gralni

### ISSUE THREAD

**Issue by Zuthen** [lplewa/unity#6]
Jeżeli będą potrzebne to również krzesła i reszta wyposażenia Gralni

**Comment by Keyti** [comment]
![laptop-left](https://user-images.githubusercontent.com/1506112/77141419-23111600-6a7d-11ea-91ed-6653bb23fc21.png)
![laptop-right](https://user-images.githubusercontent.com/1506112/77141420-23a9ac80-6a7d-11ea-9020-27e83bea2834.png)
